test : test.c affichage_du_plateau.c Lecture_fichiers_projet.c gestionGrille_action_utilisateur.c les_modes.c fonction.c
	gcc test.c affichage_du_plateau.c Lecture_fichiers_projet.c gestionGrille_action_utilisateur.c les_modes.c fonction.c -o test
